#pragma once

#include <cstddef>
#include <cstdint>
#include <concepts>
#include <iterator>
#include <string>
#include <fstream>
#include <vector>
#include <chrono>
#include <cmath>
#include <algorithm>
#include <filesystem>
#include <stack>
#include <functional>
#include <random>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <thread>
#include "kit/debug/log.hpp"

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_FORCE_INTRINSICS
#include <glm/glm.hpp>
#include <glm/gtx/norm.hpp>
#include <glm/geometric.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtx/rotate_vector.hpp>
