#pragma once

#include <unordered_map>
#include <cstddef>
#include <cstdint>
#include <string>
#include <fstream>
#include <vector>
#include <chrono>
#include <cmath>
#include <algorithm>
#include <filesystem>
#include <stack>
#include <functional>
#include <random>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <thread>
#include "kit/debug/log.hpp"

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
#include <glm/mat2x2.hpp>
#include <glm/mat3x3.hpp>
#include <glm/mat4x4.hpp>
